import PageMeta from "../../components/common/PageMeta";
import AlertsTable from "../../components/tables/Admin/AlertsTable";
import ComponentCard from "../../components/common/ComponentCard";

export default function AdminAlerts() {
  return (
    <>
      <PageMeta
        title="Alerts Management | Admin Dashboard"
        description="View all volatility alerts in the system"
      />
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-semibold text-gray-800 dark:text-white">
            Alerts Management
          </h1>
          <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
            View all volatility alerts generated by the monitor
          </p>
        </div>

        <ComponentCard title="Alerts">
          <AlertsTable />
        </ComponentCard>
      </div>
    </>
  );
}